# PlatformIO pre-build step: embed the tag firmware (../tag/hanshow_serial.bin) into the ESP32
# image so the ESP32 can flash a factory tag over SWS and keep it up to date.
import re
from pathlib import Path

Import("env")  # noqa: F821

root = Path(env["PROJECT_DIR"])  # noqa: F821
fw = (root / ".." / "tag" / "hanshow_serial.bin").resolve()
main_c = (root / ".." / "tag" / "src" / "main.c").resolve()
out = root / "src" / "tag_firmware.h"

data = fw.read_bytes()
if data[8:12] != b"KNLT":
    raise SystemExit(f"{fw} is not a Telink firmware image")
# Take the version from the image itself (its boot banner "hanshow-serial v<N>"): the ESP32 uses
# it to decide whether the tag needs updating, so it must describe the bytes actually embedded.
m = re.search(rb"hanshow-serial v(\d+)", data)
if not m:
    raise SystemExit(f"{fw}: no 'hanshow-serial v<N>' version string found")
version = int(m.group(1))
src_version = int(re.search(r'#define FW_VERSION "(\d+)"', main_c.read_text()).group(1))
if src_version != version:
    raise SystemExit(
        f"{fw} is v{version} but firmware/tag/src/main.c says v{src_version}: "
        "rebuild the tag firmware (cd firmware/tag && make) before building the ESP32 image")

body = ",".join(str(b) for b in data)
text = (
    "// Generated by embed_tag_fw.py from firmware/tag/hanshow_serial.bin - do not edit.\n"
    "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n"
    f"#define TAG_FW_BUNDLED_VERSION {version}\n"
    f"static const uint8_t TAG_FW_IMAGE[{len(data)}] = {{{body}}};\n"
)
if not out.exists() or out.read_text() != text:
    out.write_text(text)
    print(f"embedded tag firmware v{version} ({len(data)} bytes)")
