// Holiday dates. Moving dates come from holiday_tables.h (generated by tools/holiday_dates.py,
// 2026-2045); Easter, Thanksgiving and fixed dates are computed here.
#include "holidays.h"
#include "holiday_tables.h"

namespace {
const char *ZODIAC[] = {"Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake", "Horse", "Goat", "Monkey", "Rooster", "Dog", "Pig"};

int days(int y, int m, int d) {  // days since 1970-01-01 (civil calendar)
  y -= m <= 2;
  int era = y / 400, yoe = y - era * 400, doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
  return era * 146097 + yoe * 365 + yoe / 4 - yoe / 100 + doy - 719468;
}

void civil(int z, int &y, int &m, int &d) {  // inverse of days()
  z += 719468;
  int era = (z >= 0 ? z : z - 146096) / 146097, doe = z - era * 146097;
  int yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
  int doy = doe - (365 * yoe + yoe / 4 - yoe / 100), mp = (5 * doy + 2) / 153;
  d = doy - (153 * mp + 2) / 5 + 1;
  m = mp < 10 ? mp + 3 : mp - 9;
  y = yoe + era * 400 + (m <= 2);
}

int weekday(int y, int m, int d) { return (days(y, m, d) % 7 + 11) % 7; }  // 0 = Sunday

// Day offset of `today` into an entry of the table that started at most span-1 days ago, or -1.
template <typename T, size_t N> int in_table(const T (&tab)[N], int today, int span, const T **hit = nullptr) {
  for (const T &e : tab) {
    int off = today - days(e.y, e.m, e.d);
    if (off >= 0 && off < span) {
      if (hit) *hit = &e;
      return off;
    }
  }
  return -1;
}

int easter(int y, int &m) {  // anonymous Gregorian computus
  int a = y % 19, b = y / 100, c = y % 100, d = b / 4, e = b % 4, f = (b + 8) / 25, g = (b - f + 1) / 3;
  int h = (19 * a + b - d - g + 15) % 30, i = c / 4, k = c % 4, l = (32 + 2 * e + 2 * i - h - k) % 7;
  int mm = (a + 11 * h + 22 * l) / 451;
  m = (h + l - 7 * mm + 114) / 31;
  return (h + l - 7 * mm + 114) % 31 + 1;
}

Holiday make(int id, const String &greeting, const String &quip, int arg = 0) { return {id, greeting, quip, arg}; }
}  // namespace

Holiday holiday_for(int y, int m, int d, const HolidayContext &ctx) {
  int today = days(y, m, d);

  String names;  // birthdays first: they are the most personal
  int n = 0;
  bool leap = y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);
  for (int i = 0; i < ctx.n_birthdays; i++) {
    const Birthday &b = ctx.birthdays[i];
    bool on = b.month == m && (b.day == d || (!leap && m == 2 && d == 28 && b.day == 29));  // Feb 29 -> 28
    if (on && b.name.length()) {
      names += (n++ ? " & " : "") + b.name;
    }
  }
  if (n) return make(HOL_BIRTHDAY, "Happy birthday,\n" + names + "!", "Cake time!");

  if (m == 12 && d == 24) return make(HOL_CHRISTMAS, "Christmas Eve!", "Ho ho ho!");
  if (m == 12 && d == 25) return make(HOL_CHRISTMAS, "Merry Christmas!", "Ho ho ho!");
  if (m == 12 && d == 31) return make(HOL_NEW_YEAR, "New Year's Eve!", "3.. 2.. 1..");
  if (m == 1 && d == 1) return make(HOL_NEW_YEAR, "Happy " + String(y) + "!", "Hangover:\n100%");

  int em, ed = easter(y, em);
  if (m == em && d == ed) return make(HOL_EASTER, "Happy Easter!", "Hop hop!");
  const HDateNum *h = nullptr;
  if (in_table(EID_FITR, today, 1) >= 0) return make(HOL_EID_FITR, "Eid Mubarak!", "Feast time!");
  if (in_table(EID_ADHA, today, 1) >= 0) return make(HOL_EID_ADHA, "Eid al-Adha\nMubarak!", "Baa!");
  if (in_table(DIWALI, today, 1) >= 0) return make(HOL_DIWALI, "Happy Diwali!", "Let there\nbe light!");
  if (in_table(LUNAR_NY, today, 1) >= 0)
    return make(HOL_LUNAR_NY, String("Year of the ") + ZODIAC[((y - 4) % 12 + 12) % 12] + "!", "Gong xi\nfa cai!");
  if (in_table(NOWRUZ, today, 1) >= 0) return make(HOL_NOWRUZ, "Nowruz Mobarak!", "Spring is\nhere!");
  if (in_table(ROSH_HASHANAH, today, 2) >= 0) return make(HOL_ROSH_HASHANAH, "Shana Tova!", "Sweet year!");
  int night = in_table(HANUKKAH, today, 8);
  if (night >= 0) return make(HOL_HANUKKAH, "Happy\nHanukkah!", "Night " + String(night + 1) + " of 8", night + 1);
  if (in_table(HIJRI_NY, today, 1, &h) >= 0) return make(HOL_HIJRI_NY, "Happy\n" + String(h->num) + " AH!", "Blessed year!");
  if (in_table(HOLI, today, 1) >= 0) return make(HOL_HOLI, "Happy Holi!", "Wear old\nclothes!");
  if (in_table(MID_AUTUMN, today, 1) >= 0) return make(HOL_MID_AUTUMN, "Happy\nMid-Autumn!", "Mooncakes\nfor all!");
  if (m == 11 && d == 1 + (11 - weekday(y, 11, 1)) % 7 + 21)  // 4th Thursday of November
    return make(HOL_THANKSGIVING, "Happy\nThanksgiving!", "Gobble\ngobble!");
  if (m == 4 && d >= 13 && d <= 15) return make(HOL_SONGKRAN, "Happy Songkran!", "You will\nget wet!");

  if (m == 10 && d == 31) return make(HOL_HALLOWEEN, "Happy Halloween!", "Boo!");
  if (m == 2 && d == 14) return make(HOL_VALENTINE, "Happy\nValentine's!", "Be mine? <3");
  if (m == 3 && d == 17) return make(HOL_ST_PATRICK, "Happy St.\nPatrick's Day!", "Kiss me,\nI'm Irish!");
  if (m == 3 && d == 8) return make(HOL_WOMENS_DAY, "Happy Women's\nDay!", "Girl power!");
  if (m == 4 && d == 1) return make(HOL_APRIL_FOOLS, "April Fools!", "Turn me\naround ;)");
  if (m == 3 && d == 14) return make(HOL_PI_DAY, "Happy Pi Day!", "3.14159265...");

  bool june = in_table(SUMMER_SOLSTICE, today, 1) >= 0, dec = in_table(WINTER_SOLSTICE, today, 1) >= 0;
  if (june || dec) {
    if (june != ctx.south) return make(HOL_SUMMER_SOLSTICE, "Longest day\nof the year!", "Max\nsunshine!");
    return make(HOL_WINTER_SOLSTICE, "Shortest day\nof the year!", "Days grow\nlonger now");
  }
  return make(HOL_NONE, "", "");
}

Holiday holiday_next(int id, int y, int m, int d, const HolidayContext &ctx) {
  if (y <= 0) { y = 2027; m = 1; d = 1; }  // date unknown: show a sample
  for (int z = days(y, m, d), end = z + 400; z < end; z++) {  // every holiday recurs within a year
    int yy, mm, dd;
    civil(z, yy, mm, dd);
    Holiday h = holiday_for(yy, mm, dd, ctx);
    if (h.id != id) continue;
    for (;;) {  // multi-day holidays: show the main day (Jan 1 over New Year's Eve, Dec 25 over the 24th)
      if (id == HOL_HANUKKAH || id == HOL_SONGKRAN || id == HOL_ROSH_HASHANAH) return h;
      civil(++z, yy, mm, dd);
      Holiday next = holiday_for(yy, mm, dd, ctx);
      if (next.id != id) return h;
      h = next;
    }
  }
  if (id == HOL_BIRTHDAY) return make(HOL_BIRTHDAY, "Happy birthday!", "Cake time!");  // none configured
  return make(HOL_NONE, "", "");
}

const char *holiday_name(int id) {
  static const char *N[HOL_COUNT] = {
      "", "Birthdays", "New Year", "Valentine's Day", "Women's Day", "Pi Day", "St. Patrick's Day", "April Fools' Day",
      "Songkran", "Halloween", "Christmas", "Easter", "Thanksgiving", "Lunar New Year", "Mid-Autumn Festival",
      "Nowruz", "Islamic New Year", "Eid al-Fitr", "Eid al-Adha", "Rosh Hashanah", "Hanukkah", "Diwali", "Holi",
      "Summer solstice", "Winter solstice"};
  return id > HOL_NONE && id < HOL_COUNT ? N[id] : "";
}
