#!/usr/bin/env python3
"""Generate firmware/esp32/src/holiday_tables.h: dates of the moving holidays.

  pip install lunardate jdatetime hijri-converter convertdate ephem
  tools/holiday_dates.py [first_year last_year]      (default 2026 2045)

Sources: Chinese calendar (lunardate), Persian calendar (jdatetime), Umm al-Qura Hijri calendar
(hijri-converter), Hebrew calendar (convertdate), and ephem for the Hindu dates and solstices.
Diwali = the amavasya (new-moon tithi) at dusk in Delhi, at the new moon with the sun in sidereal
Tula (Lahiri ayanamsa). Holi = the day after Holika Dahan: the purnima (full-moon tithi) at dusk
of the lunar month that starts with the sun in sidereal Kumbha.
Regional observance of the Hindu and Islamic dates can differ by a day.
Easter, Thanksgiving and the fixed-date holidays are computed in holidays.cpp.
"""
import datetime as dt
import math
import sys
from pathlib import Path

import ephem
import jdatetime
from convertdate import hebrew
from hijri_converter import Gregorian, Hijri
from lunardate import LunarDate

Y0, Y1 = (int(a) for a in sys.argv[1:3]) if len(sys.argv) > 2 else (2026, 2045)
OVERRIDES = {("holi", 2026): dt.date(2026, 3, 4)}  # moved a day by the Mar 3 2026 lunar eclipse

delhi = ephem.Observer()
delhi.lat, delhi.lon, delhi.elevation = "28.6139", "77.2090", 216


def tithi(t):  # 1..30
    ls = ephem.Ecliptic(ephem.Sun(t)).lon
    lm = ephem.Ecliptic(ephem.Moon(t)).lon
    return int(((lm - ls) % (2 * math.pi)) / (2 * math.pi / 30)) + 1


def dusk_tithi(d):  # tithi 45 min after sunset in Delhi on local date d
    delhi.date = ephem.Date(dt.datetime(d.year, d.month, d.day, 6, 30))  # noon IST
    return tithi(ephem.Date(delhi.next_setting(ephem.Sun()) + 45 * ephem.minute))


def sidereal_sun(t, year):  # Lahiri ayanamsa, ~24.2 deg in 2026
    return (math.degrees(ephem.Ecliptic(ephem.Sun(t)).lon) - (24.2 + 0.014 * (year - 2026))) % 360


def moon_with_sun_in(year, first, sign_from, kind):  # first new/full moon on/after `first` whose sun sits in the sign
    t = ephem.Date(first)
    for _ in range(14):
        t = ephem.next_new_moon(t) if kind == "new" else ephem.next_full_moon(t)
        if sign_from <= sidereal_sun(t, year) < sign_from + 30:
            return t
        t += 1
    raise SystemExit(f"no {kind} moon with the sun in {sign_from} deg in {year}")


def dusk_day(t, want):  # local day around moon time t whose dusk has tithi `want`
    ist = (ephem.Date(t + 5.5 * ephem.hour)).datetime().date()
    for d in (ist - dt.timedelta(days=1), ist, ist + dt.timedelta(days=1)):
        if dusk_tithi(d) == want:
            return d
    return ist


tables = {k: [] for k in ("LUNAR_NY", "MID_AUTUMN", "NOWRUZ", "ROSH_HASHANAH", "HANUKKAH",
                          "DIWALI", "HOLI", "SUMMER_SOLSTICE", "WINTER_SOLSTICE")}
hijri = {k: [] for k in ("HIJRI_NY", "EID_FITR", "EID_ADHA")}
for y in range(Y0, Y1 + 1):
    tables["LUNAR_NY"].append(LunarDate(y, 1, 1).to_solar_date())
    tables["MID_AUTUMN"].append(LunarDate(y, 8, 15).to_solar_date())
    tables["NOWRUZ"].append(jdatetime.date(y - 621, 1, 1).togregorian())
    tables["ROSH_HASHANAH"].append(dt.date(*hebrew.to_gregorian(y + 3761, 7, 1)))
    tables["HANUKKAH"].append(dt.date(*hebrew.to_gregorian(y + 3761, 9, 25)))
    tables["DIWALI"].append(dusk_day(moon_with_sun_in(y, f"{y}/9/20", 180, "new"), 30))  # Tula
    kumbha_nm = moon_with_sun_in(y, f"{y}/1/20", 300, "new")                             # Kumbha
    holi = dusk_day(ephem.next_full_moon(kumbha_nm), 15) + dt.timedelta(days=1)
    tables["HOLI"].append(OVERRIDES.get(("holi", y), holi))
    tables["SUMMER_SOLSTICE"].append(ephem.next_solstice(f"{y}/3/1").datetime().date())
    tables["WINTER_SOLSTICE"].append(ephem.next_solstice(f"{y}/9/1").datetime().date())
h = Gregorian(Y0, 1, 1).to_hijri().year - 1
while Hijri(h, 1, 1).to_gregorian().year <= Y1:
    for key, (m, d) in (("HIJRI_NY", (1, 1)), ("EID_FITR", (10, 1)), ("EID_ADHA", (12, 10))):
        g = Hijri(h, m, d).to_gregorian()
        if Y0 <= g.year <= Y1:
            hijri[key].append((g, h))
    h += 1


def rows(items, fmt, per=5):
    return ",\n".join("    " + ", ".join(fmt(x) for x in items[i:i + per]) for i in range(0, len(items), per))


out = [f"// Generated by tools/holiday_dates.py for {Y0}-{Y1} - do not edit.", "#pragma once", "",
       "struct HDate { uint16_t y; uint8_t m, d; };",
       "struct HDateNum { uint16_t y; uint8_t m, d; uint16_t num; };  // num = Hijri year", ""]
for k, v in tables.items():
    out += [f"static const HDate {k}[] = {{", rows(v, lambda d: f"{{{d.year}, {d.month}, {d.day}}}"), "};", ""]
for k, v in hijri.items():
    out += [f"static const HDateNum {k}[] = {{", rows(v, lambda e: f"{{{e[0].year}, {e[0].month}, {e[0].day}, {e[1]}}}", 4), "};", ""]
path = Path(__file__).resolve().parent.parent / "firmware/esp32/src/holiday_tables.h"
path.write_text("\n".join(out))
print(f"wrote {path}")
